const nouns = [
    // https://www.phrases.org.uk/meanings/phrases-and-sayings-list.html
    // https://www.phrases.org.uk/meanings/nautical-phrases.html
    // aviation
    'altitudes',
    'elevations',
    // 'ailerons',

    // emotions
    'bliss',
    'sense of humor',
    'nostalgia',
    'leisure',
    'ambitiousness',
    'cheerfulness',
    'contentment',
    'curiosity',
    'delight',
    'elation',
    'enthusiasm',
    'euphoria',
    'pride',
    'achievement',
    'accomplishment',
    'pride and accomplishment',
    'senses',
    'assurances',
    'experiences',
    'wrapping paper',
    'routines',
    'hot air balloons',
    'umbrellas',

    // office
    'books',
    'frameworks',
    'libraries',
    'pencils',
    'pencil sharpeners',
    'mechanical pencils',
    'mechanical pencil lead refills',
    'erasers',
    'pens',
    'black all-purpose markers',
    'highlighters',
    'rubber stamps',
    'ink pads',
    'wall calendars',
    'desk calendars',
    'dry/wet erase boards',
    'dry/wet erase markers',
    'dry/wet erase spray',
    'rulers',
    'protractors',
    'compasses',
    't-squares',
    'clipboards',
    'bookends',
    'paperweight',
    'magazine holders',
    'bulletin board',
    'pushpins',
    'letter opener',
    'pen holder',
    'in/out box',
    'document sorter/holder',
    'supply trays and containers',
    'desktop organizers',
    'desk drawer organizers',
    'keyboard',
    'monitor stands',
    'wireless router',
    'thumb drives',
    'printer',
    'toner or print cartridges',
    'telephones',
    'speakerphone',
    'headset',
    'calculator',
    'postage meter',
    'projection device',
    'photocopiers',
    'digital camera',
    'lamps',
    'lightbulbs',
    'label makers',
    'laminating machines',
    'scanners',
    'fax machines',
    'paper shredders',
    'extension cords',
    'surge protectors',
    'walkie-talkies',
    'first-aid kits',
    'flashlights',
    'fire extinguishers',
    'smoke detectors',
    'carbon monoxide detectors',
    'desk',
    'chairs',
    'chair floor mats',
    'filing cabinets',
    'tables',
    'bookcases',
    'narratives',
    'shelves',
    'safes',
    'microwaves',
    'coffee pots',
    'refrigerators',
    'water coolers',
    'clocks',
    'waste baskets',
    'recycling bins',
    'lightbulbs',
    'composition notebooks',
    'spiral-bound notebooks',
    'legal pads',
    'steno pads',
    'notepads',
    'planners',
    'staplers',
    'staples',
    'stapler removers',
    'scissors',
    'box cutters',
    'box cutter blades',
    'paperclips (small, medium, large)',
    'binder clips (small, medium, large)',
    'rubber bands (small, medium, large)',
    'clear cellophane tape',
    'clear cellophane tape dispenser',
    'masking tape',
    'packing tape',
    'tape gun',
    'duct tape',
    'twine',
    'sticky notes (small, medium, large)',
    'bookmark sticky flags (small, medium, large)',
    'bookmarks',
    'white glue',
    'rubber cement',
    'tacky wall mount gum',
    'hanging hooks',
    'magnifying glass',
    'manila folders',
    'file folder labels',
    'hanging folders',
    'folder tabs',
    //https://www.theorderexpert.com/the-ultimate-office-supply-checklist/




    'appreciation',
    'theory',
    'theories',



    // videogames
    'joysticks',
    'controllers',
    'consoles',
    'keyboards',
    'cartridges',
    'buttons',
    'thumbsticks',

    // coding

    // interstellar/warp/space
    'warp speeds',
    'black holes',
    'skies',
    'worlds',
    'dark matter',
    'light matter',

    // sailing
    'sea shanties',
    'buoys',
    'Jolly Rogers',
    'lighthouses',
    'frigates',
    'cruisers',
    'dreadnoughts',

    // technology terms/hardware
    'CPU cores',
    'CUDA cores',
    'satellites',
    'lifespans',
    'frequencies',
    'circuit boards',
    'multi-threading',
    'transistors',
    'potentiometers',

    // audio/video/film/warp features
    'time-lapses',
    'video tracks',
    'audio tracks',
    'waveforms',
    'color-grading',
    'renders',
    'uploads',
    'downloads',

    'imports',
    'exports',
    'spectacles',
    'keyframes',
    'saturations',
    'code-bases',
    'terminals',
    'functions',
    'lenses',
    'discs',
    'synapses',
    'synthesis',
    'synthetics',
    'amusement',
    'singularities',
    'doppelgangers',
    'backgrounds',
    'galleries',
    'keywords',

    'road-trips',
    // desired things
    'applause',
    'super powers',
    'praise',

    'ruins',
    'mortals',
    'mortality',


    // music
    'chords',
    'scales',
    'lyrics',
    'melodies',
    'rhythms',
    'crescendos',

    'atoms',
    'wizardry',
    'waves',
    'capabilities',
    'realities',
    'materials',
    'nodes',
    'architecture',
    'accelerants',
    'anthropomorphism',
    'modes',
    'files',
    'media',
    'sensors',
    'humanity',
    'animations',

    // words
    'gods',

    'channels',
    'corridors',

    'mainlands',
    'portals',
    'savvy',
    'dimensions',
    'geometry',
    'cubicles',
    'attraction',
    'labs',
    'neurons',
    'sculptures',
    'scenery',
    'concepts',
    'plots',
    'stories',
    'scenarios',
    'skyscrapers',
    'sculptures',
    'towers',
    'records',
    'radios',
    'cartographers',
    'inflection points',
    'ships',
    'propellants',
    'cycles',
    'equipment',
    'themes',
    'models',
    'chapters',
    'desks',
    'mousepads',
    'quills',
    'constructs',
    'mirrors',
    'galleons',
    'overlords',
    'locomotives',
    'trains',

    // coffees
    'drip brewed coffee',
    'espresso',
    'cappuccinos',
    'lattes',
    'macchiatos',
    'mochas',
    'café au laits',
    'café mochas',
    'café lattes',



    'cloaks',
    'sentences',
    'adverbs',
    'adjectives',
    'combustion',
    'pistons',
    'jets',
    'sentiments',
    'kings',
    'queens',
    'jesters',
    'tea',
    'coffee',
    'rum',
    'film noir',

    'clusters',
    'Valhallas',
    'Lokis',
    'particle effects',
    'Thors',
    'Odins',

    'machinery',
    'comfort',
    'components',
    'windmills',
    'environments',
    'versions',
    'symbols',

    'constellations',
    'astronauts',
    'pioneers',
    'coordinates',
    'cylinders',
    'corporations',
    'artificial narrow intelligence',
    'artificial general intelligence',
    'artificial super-intelligence',
    'vinyls',
    'gramophones',
    'plot twists',
    'characters',
    'back rooms',
    'liminal spaces',
    'revolutions',
    'recordings',
    'record-players',

    'timings',

    'diagnostics',
    'subjects',
    // electronics
    'circuits',
    'microcontrollers',
    'microprocessors',
    'microchips',
    'transformers',
    'batteries',
    'fuses',
    'relays',
    'switches',
    'alchemists',
    'presentations',
    'showcases',
    'motors',
    'circuit breakers',




    'presets',
    'dark-years',
    'planets',
    'suns',
    'stars',
    'moons',
    'stratospheres',
    'atmospheres',
    'exoplanets',
    'comets',
    'asteroids',
    'meteorites',
    'meteoroid belts',
    'meteoroid fields',
    'meteoroid clusters',

    'light-years',

    'engines',
    'time-travelers',

    'event horizons',
    'fatherboards',
    'ecosystems',
    'galaxies',
    'nebulas',
    'meteor showers',
    'gas giants',
    'gas gnomes',
    'gleefulness',
    'vectors',
    'machines',
    'gravity',
    'joie de vivre',
    'joy',
    'joyfulness',
    'time-traveling',
    'reflectors',
    'refractors',
    'solstices',
    'wordplay',
    'supernovae',
    'variables',
    'tracks',
    'preferences',
    'motherboards',
    'units',
    'reserves',
    'focal lengths',
    'networks',
    'new sentences',
    'particles',
    'processor cores',
    'technologies',
    'multi-verses',
    'RAM',
    'recognition',
    'eclipses',
    'velocity',
    'rotators',
    'satisfaction',
    'schematics',
    'handsomeness',
    'intelligence',
    'apertures',
    'banter',
    'parallels',
    'molecules',
    'settings',
    'timelines',
    'interests',
    'systems',
    'blueprints',
    'sockets',
    'algorithms',
    'partitions',
    'developments',
    'kaleidoscopes',
    'drives',
    'exhilaration',
    'speeds',
    'guidance',
    'universes',
    'archetypes',

    'applications',
    'workflows',
    'exponents',
    'autodidacts',
    'analytics',
];

module.exports = nouns;