const qualifier = [
    'accompanying',
    'additional',
    'adequate',
    'alternate',
    'alternative',
    'ample',
    'auxiliary',
    'dedicated',
    'DIY',
    'extra',
    'finite',
    'increased',
    'like-new',
    'limited',
    'main',
    'near-infinite',
    'original',
    'reinforcing',
    'reserve',
    'second-hand',
    'spare',
    'spherical',
    'stand-in',
    'substantial',
    'substitute',
    'sufficient',
    'supplemental',
    'supportive',
    'several',
    'duplicate',
];


module.exports = qualifier;