/* eslint-disable no-console */
/* eslint-disable no-undef */
/* eslint-disable no-unused-expressions */
/* eslint-disable no-unused-vars */
/* eslint-disable one-var */

const logging = false;
const os = require('os');
const fs = require('fs');
const path = require('path');
const {
    app,
    BrowserView,
    BrowserWindow,
    ipcMain,
    Menu,
    MenuItem,
    shell,
    webContents,
} = require('electron');
const displayControllerReq = require('./displayController');
const appMenuAudio = require('./menuAudio');
const appMenuVideo = require('./menuVideo');
const appMenuWarpstagram = require('./menuWarpstagram');
const fileControllerReq = require('./fileController');
const fileController = new fileControllerReq();
const startupReq = require('./startup');
const startup = new startupReq();

////////////////////////////////////////////////////////////////////
let mainWindow, splash, modalWindow, displayController, storageMain; // Keep a global reference of the window object, if you don't, the window will be closed automatically when the JavaScript object is garbage collected.
app.allowRendererProcessReuse = true; // not sure what this does but I added it for a reason

////////////////////////////////////////////////////////////////////
// IPC LISTENERS FOR EVENTS FROM APP.JS
ipcMain.on('new-item', (e, itemURL, avType, platform) => {
    startup.updateActiveTab(avType); // sets nav A active
    e.reply('paste-new-url', itemURL, avType, platform); // send message to app js
});
ipcMain.on('menu-change', (e, menuType) => {
    if (menuType === 'audio') appMenuAudio(mainWindow.webContents); // sets audio menu if audio tab is clicked
    if (menuType === 'video') appMenuVideo(mainWindow.webContents); // sets video menu if video tab is clicked
    if (menuType === 'warpstagram') appMenuWarpstagram(mainWindow.webContents); // sets video menu if video tab is clicked
});
ipcMain.on('quit', () => {
    app.quit();
    mainWindow = null;
});
ipcMain.on('storage-save', (e, storageObj, avType) => {
    fileController.settingsSave('settings', storageObj);
    // console.log('saving');
    let storageAwaited;
    (async() => {
        storageAwaited = await load();
        e.reply('storage-save-success', storageAwaited);
    })();
    // console.log(storageAwaited);
});
ipcMain.on('reset-storage', (e, storageObj) => {
    fileController.reset();
    setTimeout(() => {
        mainWindow.close();
        mainWindow = null;
    }, 1000);
    app.relaunch();
    app.exit();
    // fileController.settingsSave('settings', storageObj); // #fix, wrong arg1 save name, should be 'settings'
});
const load = async() => {
    const result = await fileController.settingsLoad();
    return result;
};

////////////////////////////////////////////////////////////////////////////////////
ipcMain.on('load-storage', (e) => {
    e.reply('load-storage-success', storageMain);
});
ipcMain.on('close-app', (e) => {
    console.log('closing app...');
    app.quit();
});

////////////////////////////////////////////////////////////////////
// WINDOW CREATION
function createWindow() {
    mainWindow = new BrowserWindow({
        height: displayController.height,
        width: displayController.width,
        minWidth: displayController.minWidth,
        minHeight: displayController.minHeight,
        x: displayController.x,
        y: displayController.y,
        // height: 1200,
        // width: 1900,
        // x: 0,
        // y: 0,
        // icon: __dirname + '/icon.ico',
        // icon: __dirname + '/icon.png',
        // icon: 'C:\\Users\\Tommy\\Documents\\GitHub\\Warp-App\\icon.png',
        // icon: fileController.dirProjectPath + '/icon_black_hole.png',
        icon: fileController.dirProjectPath + '/icon_black_gradient.png',
        // icon: fileController.dirProjectPath + '/icon_black_to_white_gradient.png',
        // icon: '../../build/icon.ico',
        darkTheme: true,
        vibrancy: 'dark',
        // skipTaskbar: true,
        webPreferences: {
            nodeIntegration: true,
            worldSafeExecuteJavaScript: true,
        },
        // backgroundColor: '#0463db', // use the same color as your html file is, the main window will display this until html fully loads. This is a little better than making your app hang for a second until the html loads, then displaying the window
        // backgroundColor: '#ff8500', // use the same color as your html file is, the main window will display this until html fully loads. This is a little better than making your app hang for a second until the html loads, then displaying the window
    });

    // addDevMenu();

    mainWindow.loadFile('./src/renderer/main.html'); // Load index.html into the new BrowserWindow
    // mainWindow.loadFile('./main.html'); // Load index.html into the new BrowserWindow
    if (startup.dev.devTools) {
        mainWindow.webContents.openDevTools(); // Open DevTools - Remove for PRODUCTION!
    }

    const wc = mainWindow.webContents;
    // send stuff to app.js
    wc.on('did-finish-load', () => {
        // console.log('did-finish-load');
        // console.log(storageMain);
        wc.send('window-ready', storageMain);

        splash.destroy();
    });
    wc.on('devtools-opened', () => {});

    // Listen for window being closed
    mainWindow.on('closed', () => {
        mainWindow = null;
    });
    mainWindow.on('resize', () => {
        // console.log(`resized`);
        wc.send('resize');
    });
    mainWindow.on('move', () => {
        // console.log('window moved');
        // console.log(`Size ${mainWindow.getSize()}`);
        // console.log(`Position ${mainWindow.getPosition()}`);
    });
    mainWindow.on('maximize', () => {});
}

function createSplashWindow() {
    splash = new BrowserWindow({
        height: 300,
        width: 400,
        // x: 100,
        // y: 100,
        frame: false,
        webPreferences: {},
    });
    splash.loadFile('./src/renderer/splash.html'); // Load index.html into the new BrowserWindow
}

function createModalWindow() {
    modalWindow = new BrowserWindow({
        // parent: mainWindow,
        // modal: true,
        show: true,
        // transparent: true,
        frame: false,
        // resizable: false,
        // movable: false,
        // minimizable: false,
        // maximizable: false,
        // alwaysOnTop: true,
        // transparent: false,
        // setPosition;
        // getPosition;
        // setSize;
        // getSize;
    });
    modalWindow.loadFile('./src/renderer/modal1.html'); // Load index.html into the new BrowserWindow

    modalWindow.once('ready-to-show', () => {
        modalWindow.show();
    });
}

////////////////////////////////////////////////////////////////////
// APP LISTENERS (monitoring main node process)
app.on('ready', () => {
    createSplashWindow();
    sentenceGenerator();
    sentenceGenerator();
    sentenceGenerator();
    sentenceGenerator();
    sentenceGenerator();
    sentenceGenerator();
    sentenceGenerator();
    sentenceGenerator();
    sentenceGenerator();
    //   let splashHandler = require('../../renderer/s');
    //   splashHandler.initCanvasColor();
    //   splashHandler.render();
    displayController = new displayControllerReq(); // positions output window to display depending on single/multi-monitor
    startup.init(); // all startup checks, latest version, isOnline, hasFFmpeg etc
    fileController.init(startup); // checks for local directories and creates them if non existent
    displayController.discoverDisplay(); // discovers which display to use, 3 dev mode displayController or production
    let storageAwaited;
    // console.log(startup.settings);
    (async() => {
        storageAwaited = await load();
        // console.log('ready');
        // console.log(storageAwaited);
        storageMain = storageAwaited;
        createWindow(); // creates main app window
        // createModalWindow();
    })();
    if (startup.dev.backendOnly) mainWindow.hide(); // devMode only
});
app.on('before-quit', (event) => {
    // event.preventDefault(); //
});
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') app.quit();
});
app.on('activate', () => {
    if (mainWindow === null) createWindow(); // When app icon is clicked and app is running, (macOS) recreate the BrowserWindow
});
const advArr = [
    'Powerfully',
    'Abnormally',
    'Absentmindedly',
    'Accidentally',
    'Actually',
    'Adventurously',
    'Afterward',
    'Almost',
    'Always',
    'Annually',
    'Anxiously',
    'Arrogantly',
    'Awkwardly',
    'Bashfully',
    'Beautifully',
    'Bitterly',
    'Bleakly',
    'Blindly',
    'Blissfully',
    'Boastfully',
    'Boldly',
    'Bravely',
    'Briefly',
    'Brightly',
    'Briskly',
    'Broadly',
    'Busily',
    'Calmly',
    'Carefully',
    'Carelessly',
    'Cautiously',
    'Certainly',
    'Cheerfully',
    'Clearly',
    'Cleverly',
    'Closely',
    'Coaxingly',
    'Colorfully',
    'Continually',
    'Coolly',
    'Correctly',
    'Courageously',
    'Crossly',
    'Cruelly',
    'Curiously',
    'Daily',
    'Daintily',
    'Dearly',
    'Deceivingly',
    'Deeply',
    'Defiantly',
    'Deliberately',
    'Delightfully',
    'Diligently',
    'Dimly',
    'Doubtfully',
    'Dreamily',
    'Easily',
    'Elegantly',
    'Energetically',
    'Enormously',
    'Enthusiastically',
    'Equally',
    'Evenly',
    'Eventually',
    'Excitedly',
    'Extremely',
    'Fairly',
    'Faithfully',
    'Famously',
    'Fatally',
    'Ferociously',
    'Fervently',
    'Fiercely',
    'Fondly',
    'Foolishly',
    'Fortunately',
    'Frankly',
    'Frantically',
    'Freely',
    'Frenetically',
    'Frightfully',
    'Fully',
    'Furiously',
    'Generally',
    'Generously',
    'Gently',
    'Gladly',
    'Gleefully',
    'Gracefully',
    'Gratefully',
    'Greatly',
    'Greedily',
    'Happily',
    'Hastily',
    'Healthily',
    'Heavily',
    'Helpfully',
    'Helplessly',
    'Highly',
    'Honestly',
    'Hopelessly',
    'Hourly',
    'Hungrily',
    'Adoringly',
    'Awkwardly',
    'Beautifully',
    'Brutally',
    'Carefully',
    'Cheerfully',
    'Contentiously',
    'Crudely',
    'Deliberately',
    'Almost',
    'Barely',
    'Completely',
    'Enough',
    'Enormously',
    'Fully',
    'Greatly',
    'Practically',
    'Wholly',
    'Virtually',
    'Amazingly',
    'Appropriately',
    'Curiously',
    'Disappointingly',
    'Happily',
    'Importantly',
    'Ironically',
    'Oddly',
    'Predictably',
    'Sadly',
    'Strangely',
    'Thankfully',
    'Unpredictably',
    'Understandably',
];
const adjectiveArr = [
    'beautiful',
    'haphazard',
    'abandoned',
    'abashed',

    'abject',
    'ablaze',
    'able',
    'abnormal',
    'aboard',
    'abounding',
    'abrasive',
    'abrupt',
    'absent',

    'absurd',
    'abundant',

    'acceptable',
    'accessible',
    'accidental',
    'accurate',

    'acoustic',
    'acrid',
    'actually',
    'adamant',
    'adorable',
    'adventurous',
    'aggressive',
    'agitated',
    'alert',
    'aloof',
    'amiable',
    'amused',
    'annoyed',
    'antsy',
    'anxious',
    'appalling',
    'appetizing',
    'apprehensive',
    'arrogant',
    'ashamed',
    'astonishing',
    'attractive',
    'average',
];
const nounArr = [
    'keyboards',
    'mice',
    'start-ups',
    'adj.s',
    'beginnings',
    'boots',

    'startings',
    'launchs',
    'inaugurations',
    'starts',
    'beginnings',
    'starters',
    'implementations',
    'introductions',
    'initiations',
    'starts',
    'beginnings',
    'commencements',
    'starts',
    'beginnings',
    'launchings',
    'deployments',
    'ignitions',
    'commissionings',
    'bootings',
    'operationalizations',
    'homes',
    'power-ons',
    'hards',
    'businesses',
    'operations',
    'firms',
    'openings',
    'starts',
    'beginnings',
    'beginnings',
    'starts',
    'companys',
    'foods',
    'tears',
    'enterprises',
    'seeds',
    'hoods',
    'corporations',
    'installations',
    'undertakings',
    'pullings',
    'baselines',
    'goodwills',
    'eradications',
    'activations',
    'invocations',
    'downloads',
    'inductions',
    'strippings',
    'initiatings',
    'tearings',
    'takeoffs',
    'loadings',
    'peoples',
    'historys',
    'ways',
    'arts',
    'worlds',
    'informations',
    'maps',
    'familys',
    'governments',
    'healths',
    'systems',
    'computers',
    'meats',
    'years',
    'thankss',
    'musics',
    'persons',
    'readings',
    'methods',
    'datas',
    'foods',
    'understandings',
    'theorys',
    'laws',
    'birds',
    'literatures',
    'problems',
    'softwares',
    'controls',
    'powers',
    'abilitys',
    'economicss',
    'loves',
    'internets',
    'televisions',
    'sciences',
    'librarys',
    'natures',
    'facts',
    'products',
    'ideas',
    'temperatures',
    'investments',
    'areas',
    'societys',
    'activitys',
    'storys',
    'industrys',
    'medias',
    'things',
    'ovens',
    'communitys',
    'definitions',
    'safetys',
    'qualitys',
    'developments',
    'languages',
    'managements',
    'players',
    'varietys',
    'videos',
    'weeks',
    'securitys',
    'countrys',
    'exams',
    'movies',
    'organizations',
    'equipments',
    'physicss',
    'analysiss',
    'policys',
    'seriess',
    'thoughts',
    'basiss',
    'boyfriends',
    'directions',
    'strategys',
    'technologys',
    'armys',
    'cameras',
    'freedoms',
    'papers',
    'environments',
    'childs',
    'instances',
    'months',
    'truths',
    'marketings',
    'universitys',
    'writings',
    'articles',
    'departments',
    'goals',
    'newss',
    'audiences',
    'fishings',
    'growths',
    'incomes',
    'marriages',
    'users',
    'combinations',
    'failures',
    'medicines',
    'philosophys',
    'teachers',
    'communications',
    'nights',
    'chemistrys',
    'diseases',
    'disks',
    'energys',
    'nations',
    'roads',
    'roles',
    'soups',
    'advertisings',
    'locations',
    'successs',
    'additions',
    'apartments',
    'educations',
    'maths',
    'moments',
    'paintings',
    'politicss',
    'attentions',
    'decisions',
    'events',
    'propertys',
    'shoppings',
    'students',
    'woods',
    'competitions',
    'distributions',
    'entertainments',
    'offices',
    'populations',
    'presidents',
    'units',
    'categorys',
    'cigarettes',
    'contexts',
    'introductions',
    'opportunitys',
    'performances',
    'drivers',
    'flights',
    'lengths',
    'magazines',
    'newspapers',
    'relationships',
    'teachings',
    'cells',
    'dealers',
    'findings',
    'lakes',
    'members',
    'messages',
    'phones',
    'scenes',
    'appearances',
    'associations',
    'concepts',
    'customers',
    'deaths',
    'discussions',
    'housings',
    'inflations',
    'insurances',
    'moods',
    'womans',
    'advices',
    'bloods',
    'efforts',
    'expressions',
    'importances',
    'opinions',
    'payments',
    'realitys',
    'responsibilitys',
    'situations',
    'skills',
    'statements',
    'wealths',
    'applications',
    'citys',
    'countys',
    'depths',
    'estates',
    'foundations',
    'grandmothers',
    'hearts',
    'perspectives',
    'photos',
    'recipes',
    'studios',
    'topics',
    'collections',
    'depressions',
    'imaginations',
    'passions',
    'percentages',
    'resources',
    'settings',
    'ads',
    'agencys',
    'colleges',
    'connections',
    'criticisms',
    'debts',
    'descriptions',
    'memorys',
    'patiences',
    'secretarys',
    'solutions',
    'administrations',
    'aspects',
    'attitudes',
    'directors',
    'personalitys',
    'psychologys',
    'recommendations',
    'responses',
    'selections',
    'storages',
    'versions',
    'alcohols',
    'arguments',
    'complaints',
    'contracts',
    'emphasiss',
    'highways',
    'losss',
    'memberships',
    'possessions',
    'preparations',
    'steaks',
    'unions',
    'agreements',
    'currencys',
    'employments',
    'engineerings',
    'entrys',
    'interactions',
    'mixtures',
    'preferences',
    'regions',
    'republics',
    'traditions',
    'viruses',
    'actors',
    'classrooms',
    'deliverys',
    'devices',
    'difficultys',
    'dramas',
    'elections',
    'engines',
    'footballs',
    'guidances',
    'hotels',
    'owners',
    'prioritys',
    'protections',
    'suggestions',
    'tensions',
    'variations',
    'anxietys',
    'atmospheres',
    'awarenesss',
    'baths',
    'breads',
    'candidates',
    'climates',
    'comparisons',
    'confusions',
    'constructions',
    'elevators',
    'emotions',
    'employees',
    'employers',
    'guests',
    'heights',
    'leaderships',
    'malls',
    'managers',
    'operations',
    'recordings',
    'samples',
    'transportations',
    'charitys',
    'cousins',
    'disasters',
    'editors',
    'efficiencys',
    'excitements',
    'extents',
    'feedbacks',
    'guitars',
    'homeworks',
    'leaders',
    'moms',
    'outcomes',
    'permissions',
    'presentations',
    'promotions',
    'reflections',
    'refrigerators',
    'resolutions',
    'revenues',
    'sessions',
    'singers',
    'tenniss',
    'baskets',
    'bonuss',
    'cabinets',
    'childhoods',
    'churchs',
    'clothess',
    'coffees',
    'dinners',
    'drawings',
    'hairs',
    'hearings',
    'initiatives',
    'judgments',
    'labs',
    'measurements',
    'modes',

    'oranges',

    'possibilitys',
    'procedures',
    'queens',
    'ratios',
    'relations',
    'restaurants',
    'satisfactions',
    'sectors',
    'signatures',
    'significances',
    'songs',
    'tooths',
    'towns',
    'vehicles',
    'volumes',
    'accidents',
    'airports',
    'appointments',
    'arrivals',
    'assumptions',
    'baseballs',
    'chapters',
    'committees',
    'conversations',
    'databases',
    'enthusiasms',
    'errors',
    'explanations',

    'halls',
    'historians',
    'hospitals',
    'injurys',
    'instructions',
    'maintenances',
    'manufacturers',
    'meals',
    'perceptions',
    'pies',
    'poems',
    'presences',
    'proposals',
    'receptions',
    'replacements',
    'revolutions',
    'rivers',
    'sons',
    'speechs',
    'teas',
    'villages',
    'warnings',
    'winners',
    'workers',
    'writers',
    'assistances',
    'breaths',
    'buyers',
    'chests',
    'chocolates',
    'conclusions',
    'contributions',
    'cookies',
    'courages',
    'desks',
    'drawers',
    'establishments',
    'examinations',
    'garbages',
    'grocerys',
    'honeys',
    'impressions',
    'improvements',
    'independences',
    'insects',
    'inspections',
    'inspectors',
    'kings',
    'ladders',
    'menus',
    'penaltys',
    'pianos',
    'potatos',
    'professions',
    'professors',
    'quantitys',
    'reactions',
    'requirements',
    'salads',
    'sisters',
    'supermarkets',
    'tongues',
    'weaknesss',
    'weddings',
    'affairs',
    'ambitions',
    'analysts',
    'apples',
    'assignments',
    'assistants',
    'bathrooms',
    'bedrooms',
    'beers',
    'birthdays',
    'celebrations',
    'championships',
    'cheeks',
    'clients',
    'consequences',
    'departures',
    'diamonds',
    'dirts',
    'ears',
    'fortunes',
    'friendships',
    'funerals',
    'genes',
    'girlfriends',
    'hats',
    'indications',
    'intentions',
    'ladys',
    'midnights',
    'negotiations',
    'obligations',
    'passengers',
    'pizzas',
    'platforms',
    'poets',
    'pollutions',
    'recognitions',
    'reputations',
    'shirts',
    'sirs',
    'speakers',
    'strangers',
    'surgerys',
    'sympathys',
    'tales',
    'throats',
    'trainers',
    'uncles',
    'youths',
    'times',
    'works',
    'films',
    'waters',
    'moneys',
    'examples',
    'businesses',
    'games',
    'lifes',
    'forms',
    'airs',
    'days',
    'places',
    'numbers',
    'parts',
    'fields',
    'fishs',

    'heats',
    'hands',
    'experiences',
    'jobs',
    'books',
    'ends',
    'points',
    'types',
    'homes',
    'economys',
    'values',
    'bodys',
    'markets',
    'guides',
    'interests',
    'states',
    'radios',
    'courses',
    'companys',
    'prices',
    'sizes',
    'cards',
    'lists',
    'minds',
    'trades',
    'lines',
    'cares',
    'groups',
    'risks',
    'words',
    'fats',
    'forces',
    'keys',
    'lights',
    'trainings',
    'names',
    'schools',
    'amounts',
    'levels',
    'orders',
    'practices',
    'researchs',
    'senses',
    'services',
    'pieces',
    'webs',
    'bosss',
    'sports',
    'funs',
    'houses',
    'pages',
    'terms',
    'tests',
    'answers',
    'sounds',
    'focuss',
    'matters',
    'kinds',
    'soils',
    'boards',
    'oils',
    'pictures',
    'accesss',
    'gardens',
    'ranges',
    'rates',
    'reasons',
    'futures',
    'sites',
    'demands',
    'exercises',
    'images',
    'cases',
    'causes',
    'coasts',
    'actions',
    'ages',
    'bads',
    'boats',
    'records',
    'results',
    'sections',
    'buildings',
    'mouses',
    'cashs',
    'classes',
    'nothings',
    'periods',
    'plans',
    'stores',
    'taxs',
    'sides',
    'subjects',
    'spaces',
    'rules',
    'stocks',
    'weathers',
    'chances',
    'figures',
    'mans',
    'models',
    'sources',
    'beginnings',
    'earths',
    'programs',
    'chickens',
    'designs',
    'features',
    'heads',
    'materials',
    'purposes',
    'questions',
    'rocks',
    'salts',
    'acts',
    'births',
    'cars',
    'dogs',
    'objects',
    'scales',
    'suns',
    'notes',
    'profits',
    'rents',
    'speeds',
    'styles',
    'wars',
    'banks',
    'crafts',

    'insides',
    'outsides',
    'standards',

    'exchanges',
    'eyes',
    'fires',
    'positions',
    'pressures',

    'advantages',
    'benefits',

    'issues',

    'faces',

    'reviews',
    'rooms',
    'screens',
    'structures',
    'views',
    'accounts',
    'balls',
    'disciplines',
    'mediums',
    'shares',
    'balances',
    'bits',
    'blacks',
    'bottoms',
    'choices',
    'gifts',
    'impacts',
    'machines',
    'shapes',
    'tools',
    'winds',
    'addresss',
    'averages',
    'careers',
    'cultures',
    'mornings',
    'pots',
    'signs',
    'tables',
    'tasks',
    'conditions',
    'contacts',
    'credits',
    'eggs',
    'hopes',
    'ices',
    'networks',
    'norths',
    'squares',
    'attempts',
    'dates',
    'effects',
    'links',
    'stars',
    'voices',
    'capitals',
    'challenges',
    'friends',
    'selfs',
    'shots',
    'brushs',
    'couples',
    'debates',
    'exits',
    'fronts',
    'functions',
    'lacks',
    'livings',
    'plants',
    'plastics',
    'spots',
    'summers',
    'tastes',
    'themes',
    'tracks',
    'wings',
    'brains',
    'buttons',
    'clicks',
    'desires',
    'foots',
    'gass',
    'influences',
    'notices',
    'rains',
    'walls',
    'bases',
    'damages',
    'distances',
    'feelings',
    'pairs',
    'savingss',
    'staffs',
    'sugars',
    'targets',
    'texts',
    'animals',
    'authors',
    'budgets',
    'discounts',
    'files',
    'grounds',
    'lessons',
    'minutes',
    'officers',
    'phases',
    'references',
    'registers',
    'skys',
    'stages',
    'sticks',
    'titles',
    'troubles',
    'bowls',
    'bridges',
    'campaigns',
    'characters',
    'clubs',
    'edges',
    'evidences',
    'fans',
    'letters',
    'locks',
    'maximums',
    'novels',
    'options',
    'packs',
    'parks',

    'weights',
    'babys',
    'backgrounds',
    'carrys',
    'dishs',
    'factors',
    'fruits',
    'glasss',
    'joints',
    'masters',
    'muscles',
    'reds',
    'strengths',
    'traffics',
    'trips',
    'vegetables',
    'appeals',
    'charts',
    'gears',
    'ideals',
    'kitchens',
    'lands',
    'logs',
    'mothers',
    'nets',
    'partys',
    'principles',
    'relatives',
    'sales',
    'seasons',
    'signals',
    'spirits',
    'streets',
    'trees',
    'waves',
    'belts',
    'benchs',
    'commissions',
    'copys',
    'drops',
    'minimums',
    'paths',
    'progresss',
    'projects',
    'seas',

    'stuffs',
    'tickets',
    'tours',
    'angles',
    'blues',
    'breakfasts',
    'confidences',
    'daughters',
    'degrees',
    'doctors',
    'dots',
    'dreams',
    'dutys',
    'essays',
    'fathers',
    'fees',
    'finances',
    'hours',
    'juices',
    'limits',
    'lucks',
    'mouths',
    'peaces',
    'pipes',
    'seats',
    'stables',
    'storms',
    'substances',
    'teams',
    'tricks',
    'afternoons',
    'bats',
    'beachs',
    'blanks',
    'catchs',
    'chains',
    'considerations',
    'creams',
    'crews',
    'details',
    'golds',
    'interviews',
    'marks',
    'matchs',
    'missions',
    'pleasures',
    'scores',
    'screws',
    'sexs',
    'shops',
    'showers',
    'suits',

    'windows',
    'agents',
    'bands',

    'bones',

    'contests',
    'corners',
    'courts',
    'cups',
    'doors',
    'easts',
    'fingers',
    'garages',
    'guarantees',
    'holes',
    'hooks',
    'implements',
    'layers',
    'lectures',
    'lies',
    'manners',
    'meetings',
    'noses',
    'parkings',
    'partners',
    'profiles',
    'respects',
    'rices',
    'routines',
    'schedules',
    'swimmings',
    'telephones',
    'tips',
    'winters',
    'airlines',
    'bags',
    'battles',
    'beds',
    'bills',
    'bothers',
    'cakes',
    'codes',
    'curves',
    'designers',
    'dimensions',
    'dresss',
    'eases',
    'emergencys',
    'evenings',
    'extensions',
    'farms',
    'fights',
    'gaps',
    'grades',
    'holidays',
    'horrors',
    'horses',
    'hosts',
    'husbands',
    'loans',
    'mistakes',
    'mountains',
    'nails',
    'noises',
    'occasions',
    'packages',
    'patients',
    'pauses',
    'phrases',
    'proofs',
    'races',
    'reliefs',
    'sands',
    'sentences',
    'shoulders',
    'smokes',
    'stomachs',
    'strings',
    'tourists',
    'towels',
    'vacations',
    'wests',
    'wheels',
    'wines',
    'arms',
    'asides',
    'associates',
    'bets',
    'blows',
    'brothers',
    'buddys',
    'chips',
    'coachs',
    'documents',
    'drafts',
    'dusts',
    'experts',
    'floors',
    'gods',
    'golfs',
    'habits',
    'irons',
    'judges',
    'knifes',
    'landscapes',
    'leagues',
    'openings',
    'parents',
    'patterns',
    'pins',
    'pools',
    'pounds',
    'requests',
    'salarys',
    'shames',
    'shelters',
    'shoes',
    'silvers',
    'tackles',
    'tanks',
    'trusts',
    'assists',
    'bars',
    'bells',
    'bikes',
    'blames',
    'boys',
    'bricks',
    'chairs',
    'closets',
    'clues',
    'collars',
    'comments',
    'conferences',
    'devils',
    'diets',
    'fears',
    'fuels',
    'gloves',
    'jackets',
    'lunchs',
    'monitors',
    'mortgages',
    'nurses',
    'paces',
    'panics',
    'peaks',
    'planes',
    'rewards',
    'rows',
    'sandwichs',
    'shocks',
    'spites',
    'sprays',
    'surprises',
    'tills',
    'transitions',
    'weekends',
    'welcomes',
    'yards',
    'alarms',
    'bends',
    'bicycles',
    'bites',
    'blinds',
    'bottles',
    'cables',
    'candles',
    'clerks',
    'clouds',
    'concerts',
    'counters',
    'flowers',
    'grandfathers',
    'harms',
    'knees',
    'lawyers',
    'leathers',
    'loads',
    'mirrors',
    'necks',
    'pensions',
    'plates',
    'purples',
    'ruins',
    'ships',
    'skirts',
    'slices',
    'snows',
    'specialists',
    'strokes',
    'switchs',
    'trashs',
    'tunes',
    'zones',
    'angers',
    'awards',
    'bids',
    'bitters',
    'boots',
    'bugs',
    'camps',
    'candys',
    'carpets',
    'cats',
    'champions',
    'channels',
    'clocks',
    'comforts',
    'cows',
    'cracks',
    'engineers',
    'entrances',
    'faults',
    'grasss',
    'guys',
    'hells',
    'highlights',
    'incidents',
    'islands',
    'jokes',
    'jurys',
    'legs',
    'lips',
    'mates',
    'motors',
    'nerves',
    'passages',
    'pens',
    'prides',
    'priests',
    'prizes',
    'promises',
    'residents',
    'resorts',
    'rings',
    'roofs',
    'ropes',
    'sails',
    'schemes',
    'scripts',
    'socks',
    'stations',
    'toes',
    'towers',
    'trucks',
    'witnesss',
    'as',
    'yous',
    'its',
    'cans',
    'wills',
    'ifs',
    'manys',
    'mosts',
    'others',
    'uses',
    'makes',
    'goods',
    'looks',
    'helps',

    'greats',
    'beings',

    'humans',
    'locals',
    'generals',

    'specifics',
    'longs',
    'plays',
    'feels',
    'highs',

    'puts',

    'sets',
    'changes',

    'pasts',
    'bigs',
    'possibles',
    'particulars',
    'todays',
    'majors',

    'physicals',
    'shows',
    'trys',
    'checks',
    'seconds',
    'calls',
    'moves',
    'pays',
    'lets',
    'increases',
    'singles',
    'individuals',
    'turns',
    'asks',
    'buys',
    'guards',
    'holds',
    'mains',
    'offers',
    'potentials',
    'professionals',
    'internationals',
    'travels',
    'cooks',
    'alternatives',
    'followings',
    'specials',
    'workings',
    'wholes',
    'dances',
    'excuses',
    'colds',
    'commercials',
    'lows',
    'purchases',
    'deals',
    'primarys',
    'worths',
    'falls',
    'necessarys',
    'positives',
    'produces',
    'searchs',
    'presents',
    'spends',
    'talks',
    'creatives',
    'tells',
    'costs',
    'drives',
    'greens',
    'supports',
    'glads',
    'removes',
    'returns',
    'runs',
    'complexs',
    'dues',
    'effectives',
    'middles',
    'regulars',
    'reserves',
    'independents',
    'leaves',
    'originals',
    'reachs',
    'rests',
    'serves',
    'watchs',
    'beautifuls',
    'charges',
    'actives',
    'breaks',
    'negatives',
    'safes',
    'stays',
    'visits',
    'visuals',

    'reports',

    'juniors',
    'picks',
    'uniques',
    'anythings',
    'classics',
    'finals',

    'westerns',
    'concerns',
    'familiars',
    'flys',
    'officials',
    'broads',
    'comfortables',
    'gains',
    'maybes',
    'richs',
    'saves',
    'stands',
    'youngs',
    'fails',
    'heavys',
    'hellos',
    'leads',
    'listens',
    'valuables',
    'worrys',
    'handles',
    'leadings',
    'meets',
    'releases',
    'sells',
    'finishs',
    'normals',
    'presss',
    'rides',
    'secrets',
    'spreads',
    'springs',
    'toughs',
    'waits',
    'browns',
    'deeps',
    'displays',
    'flows',
    'hits',
    'objectives',
    'shoots',
    'touchs',
    'cancels',
    'chemicals',
    'crys',
    'dumps',
    'extremes',
    'pushs',
    'conflicts',
    'eats',

    'formals',
    'jumps',
    'kicks',
    'opposites',

    'remotes',

    'treats',

    'beats',
    'burns',
    'deposits',
    'prints',
    'raises',
    'sleeps',
    'somewheres',
    'advances',
    'anywheres',
    'consists',
    'darks',
    'doubles',
    'draws',
    'equals',
    'fixs',
    'hires',
    'internals',
    'joins',
    'kills',
    'sensitives',
    'taps',
    'wins',
    'attacks',
    'claims',
    'constants',
    'drags',
    'drinks',
    'guesss',
    'minors',
    'pulls',
    'raws',
    'softs',
    'solids',
    'wears',
    'weirds',
    'wonders',
    'annuals',
    'counts',
    'deads',
    'doubts',
    'feeds',
    'forevers',
    'impresss',
    'nobodys',
    'repeats',
    'rounds',
    'sings',
    'slides',

    'wishs',
    'combines',
    'commands',
    'digs',
    'equivalents',

    'smells',
    'spirituals',
    'surveys',
    'ties',
    'adults',
    'briefs',
    'crazys',
    'escapes',
    'gathers',
    'hates',
    'priors',
    'repairs',
    'roughs',
    'sads',
    'scratchs',
    'sicks',
    'strikes',
    'employs',
    'externals',
    'hurts',
    'illegals',
    'laughs',

    'mobiles',

    'strains',
    'struggles',
    'swims',
    'trains',
    'uppers',
    'washs',
    'yellows',
    'converts',
    'crashs',
    'dependents',
    'folds',
    'grabs',
    'hides',

    'permits',
    'quotes',

    'rolls',

    'spares',
    'suspects',
    'sweets',

    'estimates',
    'grands',
    'males',
    'mines',
    'prompts',
    'quiets',
    'refusals',
    'regrets',
    'reveals',
    'rushs',
    'shakes',
    'shifts',
    'shines',
    'steals',
    'sucks',
    'surrounds',
    'anybodys',
    'bears',
    'brilliants',
    'dares',
    'dears',
    'delays',

    'hurrys',
    'inevitables',
    'invites',
    'kisss',
    'neats',
    'pops',
    'punchs',
    'quits',
    'replys',
    'representatives',
    'resists',
    'rips',
    'rubs',
    'sillys',
    'smiles',
    'spells',
    'stretchs',
    'stupids',
    'tomorrows',

    'storages',
    'interfaces',
];
const verbArr = [
    'notwithstanding',
    'multiprocessing',
    'superconducting',
    'uncomprehending',

    'misapprehending',
    'weatherproofing',
    'overwithholding',
    'inconveniencing',
    'overprescribing',
    'oversubscribing',
    'preestablishing',
    'counterpunching',

    'counterstriking',
    'restrengthening',
    'counterclaiming',
    'sledgehammering',
    'counterordering',
    'overengineering',
    'decommissioning',
    'recommissioning',
    'preconditioning',
    'reconsolidating',
    'excommunicating',

    'disintoxicating',
    'reinvestigating',
    'melodramatising',
    'revolutionising',
    'particularising',
    'industrialising',
    'commercialising',
    'conceptualising',
    'individualising',
    'remanufacturing',
    'straitjacketing',
    'interconnecting',
    'interdigitating',
    'overelaborating',
    'deconcentrating',
    'reconcentrating',
    'reincorporating',
    'supersaturating',
    'proportionating',
    'compassionating',
    'procrastinating',
    'decontaminating',

    'underestimating',
    'differentiating',
    'misinterpreting',
    'troubleshooting',
];
const randomFromArray = (arr) => {
    randomItem = arr[Math.floor(Math.random() * Math.floor(arr.length - 1))];
    // console.log(randomItem);
    return randomItem;
};
const sentenceGenerator = () => {
    let randomAdv = randomFromArray(advArr);
    let randomAdj = randomFromArray(adjectiveArr);
    let randomNoun = randomFromArray(nounArr);
    let randomVerb = randomFromArray(verbArr);
    console.log(`${randomAdv} ${randomVerb} ${randomAdj} ${randomNoun}...`);
};