const adjDegreeArr = [
    'blatantly',
    'brazenly',
    'briefly',
    'deeply',
    'enough',
    'fairly',
    'generally',
    'highly',
    'intensely',
    'kind of',
    'massively',
    'moderately',
    'more or less',
    'mostly',
    'nearly',
    'often',
    'overly',
    'partially',
    'partly',
    'pretty',
    'procedurally',
    'quite',
    'rather',
    'regularly',
    'relatively',
    'seemingly',
    'slightly',
    'solidly',
    'sometimes',
    'somewhat',
    'somewhat',
    'sort of',
    'strangely',
];

module.exports = adjDegreeArr;