const adjectiveDescriptiveArr = [
    // emotions/attitudes
    'happy',
    'nostalgic',
    'euphoric',
    'playful',
    'friendly',
    'determined',
    'energetic',
    'procrastinating',
    'resourceful',
    'sweet',
    'irreverent',
    'wholesome',
    'effervescent',
    'anthropomorphic',
    'animated',
    'self-directed',
    'self-aware',

    // human characteristics
    'autodidactic',
    'ambitious',

    // time
    '80\'s',
    '90\'s',
    '70\'s',
    'futuristic',
    'vintage',
    'classic',
    'human-like',
    'asynchronous',
    'synchronous',

    // IMPORTANCE
    'primary',
    'secondary',
    'relevant',

    // visual

    'colorful',
    'colorless',
    'monochrome',
    'multicolored',
    'attractive',
    'profound',

    // tech
    'overclocked',
    'analog',
    '10-core',
    'hexa-core',
    'octo-core',
    'solid state',
    'offline',
    'online',
    'quad-core',
    'VHS',
    'low-level',
    'high-level',
    'algorithmic',
    'mono',
    'surrounding',
    'streaming',
    'wireframe',
    'disconnected',
    'un-socketed',
    'vertexed',
    'multi-threaded',
    '384-bit',
    'peer-to-peer',
    'cascading',
    'socketed',
    'computing',
    'de-computing',



    // film/movies
    'time-lapse',
    'Terminator-like',
    'Thor-like',
    'Odin-like',
    'Loki-like',

    // space
    '2-dimensional',
    '3-dimensional',
    '4-dimensional',
    'solar',
    'astronomical',
    'space',
    'radio',


    'outer',
    'color-graded',
    'director\'s cut',
    'inner',
    'exterior',
    'interior',





    // condition
    'refurbished',
    'clean',
    'salvaged',
    'formatted',
    'un-formatted',

    // sound
    'stereo',
    'audible',
    'mono',
    'quiet',
    'noisy',
    'rhythmic',

    // sailing
    'starboard',
    'port-side',
    'below-decks',
    'above-decks',
    'ocean-bound',
    'windward',
    'leeward',
    'anchored',


    // perspective/philosophical
    'subjective',

    // musical
    'synthwave',
    'rock-n-roll',
    'jazz',
    'classical',
    'avant-garde',
    'ballet',
    'baroque',
    'cantata',
    'choral',
    'classical crossover',
    'concerto',
    'concerto grosso',
    'contemporary classical',
    'early',
    'expressionist',
    'high classical',
    'impressionist',
    'medieval',
    'minimalist',
    'modern compositional',
    'modern classical',
    'operatic',
    'oratorio',
    'orchestral',
    'renaissance',
    'romantic',
    'symphonic',
    'twelve-tone',


    // other
    'archetypical',
    'static',

    // words
    'godly',
    // gaming

    // location/navigation/where/position
    'latitudinal',
    'longitudinal',
    'internal',
    'routine',
    'external',
    'subterranean',

    'radial',
    'cylindrical',
    'savvy',
    'geometrical',
    'gaming',
    'morphed',
    'whimsical',
    'flying',
    'caffeinated',
    'spherical',
    'shapeshifting',
    'polygonal',
    'expansion',
    'architectural',
    'unparalleled',
    'noteworthy',
    'exceptional',
    'astonishing',
    'thunderous',
    'personal',
    'open',
    'similar',
    'opposing',
    'developer',
    'closed',
    'modular',
    'compatible',
    'unique',
    'extraordinary',
    'invaluable',
    'connected',

    // visual
    'aesthetic',
    'cosmetic',
    'cinematic',
    'invisible',
    'transparent',
    'translucent',
    'opaque',


    // SIZE/shape
    'compact',
    'giant',
    'colossal',
    'tiny',
    'elongated',
    'proportional',


    // status/status
    'unprocessed',

    'thermostatic',
    'behavioral',
    'liquid',
    'guided',
    'accelerative',
    'thermodynamic',
    'preset',
    'pre-determined',
    'fully-managed',
    'genuine',
    'extraordinary',
    'separated',
    'distributed',
    'centralized',
    'de-centralized',

    'functional',
    'synaptic',
    'processed',
    'blissful',
    'non-synthetic',
    'packaged',
    'proxy',
    'hand-crafted',
    'machine',
    'power',
    'emergent',
    'multi-versed',
    'aligned',
    'entertaining',
    'supercharged',
    'doppelganger',
    'intelligent',
    'expanded',
    'developed',
    'gravitational',
    'kaleidoscopic',
    'logical',
    'logistical',
    'interesting',

    'procedural',
    'blended',

    'shaded',
    'partial',
    'partitioned',
    'proximity',
    'artificial',
    'authentic',
    'certified',
    'sensible',
    'enjoyable',
    'heavy',
    'twin',
    'triplicate',
    'duplicate',
    'quadruple',
    'beautiful',
    'handsome',
    'light-duty',
    'heavy-duty',
    'declarative',
    'controlled',
    'retro',
    'retrograde',
    'retroactive',

    'modified',


    'asymmetric',
    'symmetrical',
    'parallel',
    'quantum',
    '64-bit',
    '32-bit',
    '8-bit',
    '16-bit',
    '128-bit',
    'atomic',
    'backup',
    '2.9Ghz',
    '3.0Ghz',
    '5 nanometer',
    '50mm',
    'invested',
    '700mm',
    '105mm',
    '20mm',
    '80mm',

    'breathtaking',
    'definitive',
    'defined',
    'reactive',
    'clustered',
    'meteoric',
    'balanced',
    'considerable ',
    'contented',
    'light',
    'compound',
    'extensive',
    'complex',
    'simple',
    'cozy',
    'critical ',
    'crucial ',
    'parallax',
    'load-balancing',
    'circumpolar',
    'exhilarating',
    'curious',
    'dynamic',
    'inclined',
    'variable',
    'electromagnetic',
    'essential ',
    'exceptional ',
    'extensive ',
    'galactic',
    'high-caliber ',
    'imaginative',
    'positive',
    'collected',
    'exhilarated',
    'uncollected',
    'technological',
    // importance
    'imperative ',
    'influential ',
    'infrared',
    'interplanetary',
    'interstellar',
    'lively',
    'lunar',
    'reasonable',
    'meaningful ',
    'exponential',
    'necessary ',
    'networked',
    'spontaneous',
    'un-spontaneous',
    'nuclear',
    'rotating',
    'aquatic',
    'enigmatic',
    'spatial',
    'space-time',
    'orbital',

    'potent',
    'contented',
    'phased',
    'jovial',
    'quasar',
    'molecular',
    'reflective',
    'refractive',



    'project',
    'supplied',
    'un-supplied',

    'meta',
    'serverless',
    'serious',
    'significant',
    'routed',

    'stupendous',
    'concentrated',
    'condensed',
    'compressed',
    'telescopic',
    'prerequisite',
    'elective',

    'weapons-grade ',
    'companion',
    'focal',


];

module.exports = adjectiveDescriptiveArr;