const adjectiveDescriptiveArr = [
    // emotions
    'happy',
    'nostalgic',
    'euphoric',
    'playful',
    'friendly',

    // human characteristics
    'learning',
    'autodidactic',
    'ambitious',

    // time
    '80\'s',
    '90\'s',
    '70\'s',
    'futuristic',
    'vintage',
    'classic',

    // tech
    'A/V',
    'overclocked',
    'analog',
    'audio',
    'deca-core',
    'hexa-core',
    'octo-core',
    'solid state',
    'offline',
    'online',
    'quad-core',
    'video',
    'VHS',
    'formatted',
    'unformatted',
    'algorithmic',
    'mono',
    'surrounding',
    'streaming',
    'wireframe',
    'disconnected',
    'socketed',
    'un-socketed',
    'vertexed',
    'multi-threaded',
    '384-bit',
    'peer-to-peer',

    // film
    'time-lapse',

    // space
    '2-dimensional',
    '3-dimensional',
    '4-dimensional',
    'solar',

    // size
    'giant',

    // condition
    'refurbished',
    'clean',
    'salvaged',

    // sound
    'stereo',
    'audible',
    'mono',
    'quiet',
    'noisy',

    // sailing
    'starboard',
    'port-side',
    'below-decks',
    'above-decks',
    'ocean-bound',
    'windward',
    'leeward',
    // other
    'archetypical',
    'static',

    'internal',
    'external',
    'expansion',
    'architectural',
    'synthwave',
    'personal',
    'open',
    'similar',
    'opposing',
    'closed',
    'modular',
    'compatible',
    'jazz',
    'connected',
    'up up down down left right left right B A',
    'latitudinal',
    'longitudinal',



    'thermostatic',
    'liquid',
    'guided',
    'accelerative',
    'thermodynamic',
    'preset',
    'pre-determined',
    'fully-managed',
    'astronomical',
    'genuine',
    'separated',
    'distributed',
    'centralized',
    'de-centralized',
    'low-level',
    'high-level',
    'cosmetic',
    'aesthetic',
    'synchronous',
    'functional',
    'synaptic',
    'asynchronous',
    'processed',
    'blissful',
    'unprocessed',
    'non-synthetic',
    'packaged',
    'proxy',
    'hand-crafted',
    'machine',
    'power',
    'multi-versed',
    'aligned',
    'entertaining',
    'supercharged',
    'doppelganger',
    'compact',
    'intelligent',
    'expanded',
    'developed',
    'gravitational',
    'kaleidoscopic',
    'logical',
    'logistical',
    'interesting',
    'cascading',

    'procedural',
    'blended',

    'shaded',
    'partial',
    'partitioned',
    'proximity',
    'artificial',
    'authentic',
    'certified',
    'sensible',
    'snug',
    'enjoyable',
    'heavy',
    'twin',
    'triple',
    'tiny',
    'double',
    'quadruple',
    'beautiful',
    'handsome',
    'light-duty',
    'heavy-duty',
    'declarative',
    'controlled',
    'retro',
    'retrograde',
    'retroactive',

    'modified',


    'asymmetric',
    'symmetrical',
    'parallel',
    'quantum',
    '64-bit',
    '32-bit',
    '8-bit',
    '16-bit',
    '128-bit',
    'atomic',
    'backup',
    '2.9Ghz',
    '3.0Ghz',
    '5 nanometer',
    '50mm',
    'invested',
    '700mm',
    '105mm',
    '20mm',
    '80mm',

    'breathtaking',
    'definitive',
    'defined',
    'reactive',
    'clustered',
    'meteoric',
    'balanced',
    'considerable ',
    'contented',
    'light',
    'compound',
    'extensive',
    'complex',
    'simple',
    'cozy',
    'critical ',
    'crucial ',
    'parallax',
    'load-balancing',
    'transparent',
    'circumpolar',
    'exhilarating',
    'curious',
    'dynamic',
    'inclined',
    'variable',
    'electromagnetic',
    'essential ',
    'exceptional ',
    'extensive ',
    'galactic',
    'high-caliber ',
    'imaginative',
    'positive',
    'collected',
    'exhilarated',
    'uncollected',
    'technological',
    'elongated',
    'imperative ',
    'influential ',
    'infrared',
    'interplanetary',
    'interstellar',
    'lively',
    'lunar',
    'reasonable',
    'meaningful ',
    'exponential',
    'necessary ',
    'networked',
    'spontaneous',
    'un-spontaneous',
    'nuclear',
    'rotating',
    'spatial',
    'space-time',
    'orbital',

    'potent',
    'contented',
    'phased',
    'jovial',
    'quasar',
    'molecular',
    'reflective',
    'refractive',
    'primary',
    'computing',
    'de-computing',
    'project',
    'supplied',
    'un-supplied',
    'relevant',
    'secondary',
    'serious',
    'significant',
    'routing',

    'stupendous',
    'concentrated',
    'condensed',
    'compressed',
    'telescopic',
    'prerequisite',
    'elective',

    'weapons-grade ',
    'companion',
    'focal',


];

module.exports = adjectiveDescriptiveArr;