const nouns = [
    // aviation
    'altitudes',
    'ailerons',

    // emotions
    'bliss',
    'sense of humor',
    'nostalgia',
    'leisure',
    'ambitiousness',
    'cheer',
    'cheerfulness',
    'contentment',
    'curiosity',
    'delight',
    'elation',
    'enjoyment',
    'enthusiasm',
    'euphoria',



    // videogames
    'joysticks',
    'controllers',
    'consoles',
    'keyboards',
    'cartridges',

    // coding

    // interstellar/warp/space
    'warp speeds',
    'black holes',

    // sailing
    'sea shanties',

    // technology terms/hardware
    'CPU cores',
    'CUDA cores',
    'satellites',
    'circuit boards',
    'multi-threading',
    'transistors',
    'potentiometers',

    // audio/video/film/warp features
    'time-lapses',

    'code-bases',
    'terminals',
    'functions',
    'discs',
    'synapses',
    'synthesis',
    'riddles',
    'synthetics',
    'amusement',
    'doppelgangers',

    // desired things
    'applause',
    'super powers',
    'praise',

    'atoms',
    'wizardry',
    'waves',
    'capabilities',
    'realities',
    'materials',
    'nodes',
    'architecture',
    'accelerants',
    'modes',
    'files',
    'media',
    'channels',
    'equipment',

    'clusters',
    'comfort',
    'components',
    'constellations',
    'coordinates',

    'diagnostics',


    'presets',
    'dark-years',
    'light-years',
    'engines',
    'time-travelers',

    'event horizons',
    'fatherboards',
    'ecosystems',
    'galaxies',
    'nebulas',
    'meteor showers',
    'gas giants',
    'gas gnomes',
    'gleefulness',
    'machines',
    'gravity',
    'joie de vivre',
    'joy',
    'joyfulness',
    'time-traveling',
    'reflectors',
    'refractors',
    'solstices',
    'supernovae',
    'variables',
    'tracks',
    'preferences',
    'motherboards',
    'units',
    'reserves',
    'focal lengths',
    'networks',
    'new sentences',
    'particles',
    'processor cores',
    'technologies',
    'multi-verses',
    'RAM',
    'recognition',
    'eclipses',
    'velocity',
    'rotators',
    'satisfaction',
    'schematics',
    'handsomeness',
    'intelligence',
    'apertures',
    'banter',
    'parallels',
    'molecules',
    'settings',
    'timelines',
    'interests',
    'systems',
    'blueprints',
    'sockets',
    'algorithms',
    'partitions',
    'development',
    'kaleidoscopes',
    'drives',
    'exhilaration',
    'speeds',
    'guidance',
    'universes',
    'archetypes',

    'applications',
    'workflows',
    'exponents',
    'autodidacts',
    'analytics',
];

module.exports = nouns;