const nouns = [
    // aviation
    'altitudes',
    // 'ailerons',

    // emotions
    'bliss',
    'sense of humor',
    'nostalgia',
    'leisure',
    'ambitiousness',
    'cheerfulness',
    'contentment',
    'curiosity',
    'delight',
    'elation',
    'enthusiasm',
    'euphoria',
    'pride',
    'achievement',
    'accomplishment',
    'pride and accomplishment',
    'senses',
    'assurances',
    'experiences',
    'routines',


    'appreciation',
    'theory',
    'theories',



    // videogames
    'joysticks',
    'controllers',
    'consoles',
    'keyboards',
    'cartridges',
    'buttons',
    'thumbsticks',

    // coding

    // interstellar/warp/space
    'warp speeds',
    'black holes',
    'skies',
    'worlds',
    'dark matter',
    'light matter',

    // sailing
    'sea shanties',
    'buoys',
    'lighthouses',

    // technology terms/hardware
    'CPU cores',
    'CUDA cores',
    'satellites',
    'circuit boards',
    'multi-threading',
    'transistors',
    'potentiometers',

    // audio/video/film/warp features
    'time-lapses',
    'video tracks',
    'audio tracks',
    'waveforms',
    'color-grading',
    'renders',
    'imports',
    'exports',
    'code-bases',
    'terminals',
    'functions',
    'discs',
    'synapses',
    'synthesis',
    'synthetics',
    'amusement',
    'singularities',
    'doppelgangers',

    // desired things
    'applause',
    'super powers',
    'praise',

    'atoms',
    'wizardry',
    'waves',
    'capabilities',
    'realities',
    'materials',
    'nodes',
    'architecture',
    'accelerants',
    'anthropomorphism',
    'modes',
    'files',
    'media',
    'sensors',
    'humanity',
    'animations',

    // words
    'gods',

    'channels',
    'savvy',
    'geometry',
    'radios',
    'ships',
    'propellants',
    'cycles',
    'equipment',

    'clusters',
    'machinery',
    'comfort',
    'components',
    'constellations',
    'coordinates',
    'cylinders',

    'diagnostics',


    'presets',
    'dark-years',
    'planets',
    'stratospheres',
    'atmospheres',
    'light-years',

    'engines',
    'time-travelers',

    'event horizons',
    'fatherboards',
    'ecosystems',
    'galaxies',
    'nebulas',
    'meteor showers',
    'gas giants',
    'gas gnomes',
    'gleefulness',
    'vectors',
    'machines',
    'gravity',
    'joie de vivre',
    'joy',
    'joyfulness',
    'time-traveling',
    'reflectors',
    'refractors',
    'solstices',
    'wordplay',
    'supernovae',
    'variables',
    'tracks',
    'preferences',
    'motherboards',
    'units',
    'reserves',
    'focal lengths',
    'networks',
    'new sentences',
    'particles',
    'processor cores',
    'technologies',
    'multi-verses',
    'RAM',
    'recognition',
    'eclipses',
    'velocity',
    'rotators',
    'satisfaction',
    'schematics',
    'handsomeness',
    'intelligence',
    'apertures',
    'banter',
    'parallels',
    'molecules',
    'settings',
    'timelines',
    'interests',
    'systems',
    'blueprints',
    'sockets',
    'algorithms',
    'partitions',
    'developments',
    'kaleidoscopes',
    'drives',
    'exhilaration',
    'speeds',
    'guidance',
    'universes',
    'archetypes',

    'applications',
    'workflows',
    'exponents',
    'autodidacts',
    'analytics',
];

module.exports = nouns;