const nouns = [
    'ambitiousness',
    'praise',
    'satellites',
    'time-lapses',
    'discs',
    'synapses',
    'synthesis',
    'synthetics',
    'amusement',
    'doppelgangers',
    'applause',
    'atoms',
    'waves',
    'multi-threading',
    'bliss',
    'functions',
    'black holes',
    'super powers',
    'capabilities',
    'materials',
    'architecture',
    'accelerants',
    'modes',
    'sea shanties',
    'files',
    'media',
    'channels',
    'equipment',
    'cheer',
    'cheerfulness',
    'circuit boards',
    'clusters',
    'comfort',
    'components',
    'constellations',
    'coordinates',
    'joysticks',
    'controllers',
    'keyboards',
    'cartridges',
    'contentment',
    'diagnostics',
    'CPU cores',
    'CUDA cores',
    'curiosity',
    'presets',
    'delight',
    'elation',
    'dark-years',
    'light-years',
    'engines',
    'time-travelers',
    'enjoyment',
    'enthusiasm',
    'euphoria',
    'event horizons',
    'fatherboards',
    'ecosystems',
    'galaxies',
    'nebulas',
    'meteor showers',
    'gas giants',
    'gas gnomes',
    'gleefulness',
    'machines',
    'gravity',
    'joie de vivre',
    'joy',
    'joyfulness',
    'time-traveling',
    'reflectors',
    'refractors',
    'solstices',
    'supernovae',
    'leisure',
    'variables',
    'tracks',
    'preferences',
    'motherboards',
    'units',
    'reserves',
    'focal lengths',
    'networks',
    'new sentences',
    'particles',
    'processor cores',
    'technologies',
    'multi-verses',
    'RAM',
    'recognition',
    'eclipses',
    'velocity',
    'rotators',
    'satisfaction',
    'sense of humor',
    'schematics',
    'handsomeness',
    'intelligence',
    'apertures',
    'banter',
    'parallels',
    'molecules',
    'settings',
    'timelines',
    'interests',
    'systems',
    'blueprints',
    'sockets',
    'algorithms',
    'partitions',
    'development',
    'kaleidoscopes',
    'drives',
    'exhilaration',
    'speeds',
    'guidance',
    'universes',
    'archetypes',
    'transistors',
    'potentiometers',
    'applications',
    'nostalgia',
    'workflows',
    'exponents',
    'autodidacts',
    'logistics',
    'analytics',
];

module.exports = nouns;