 const verbs = [
     'adding fuel to',
     'applying',
     'arranging',
     'blueprinting',
     'brewing coffee for',
     'inventing',
     'checking',
     'compiling',
     'composing',
     'reviving',
     'revising',
     'constructing',
     'creating',
     'designing',
     'developing',
     'diagramming',
     'upgrading',
     'downloading',
     'materializing',
     'teleporting',
     'drawing',
     'refurbishing',
     'editing',
     'engineering',
     'establishing',
     'exploring',
     'expanding',
     'forming',
     'fueling',
     'generating',
     're-inventing',
     'installing',
     'loading',
     'mapping',
     'initializing',
     'manufacturing',
     'balancing',
     'rendering',
     'synthesizing',
     'initiating',
     'resolving',
     'engaging',
     'running',
     'mining for',
     'modeling',
     'coordinating',
     'publishing',
     'optimizing',
     'buccaneering',
     'authoring',
     'charting',
     'supercharging',
     'planning',
     'pre-compiling',
     'pre-computing',
     'preparing',
     'diagnosing',
     'securing',
     'preparing',
     'looking up',
     'saving',
     'reading',
     'propagating',
     'releasing',
     'mustering',
     'conveying',
     'inspecting',
     'scrubbing',
     'maintaining',
     'cleaning',
     'dusting',
     'accelerating',
     'cranking on',
     'multiplying',
     'refining',
     'rescuing',
     'populating',
     'awaiting',
     'compressing',
     'seeking',
     'spawning',
     'charging',
     'shoveling coal into',
     'showing off',
     'spinning up',
     'spooling up',
     'aligning',
     'updating',
     'waking up',
     'extending',
     'warming up',
 ];

 module.exports = verbs;