const downloadsAudioDefaults = [
  {
    date: new Date(2021, 11, 26, 16, 44, 10),
    format: 'wav',
    id: '2',
    length: '00:54:32',
    size: '3.2 MB',
    source: 'vimeo',
    thumbnail: 'https://i3.ytimg.com/vi/OulXMB4W5B0/maxresdefault.jpg',
    title: 'The Wonder Years',
    type: 'audio',
    url: 'https://www.youtube.com/watch?v=uq-_-RJt-E8',
  },
  {
    date: new Date(2020, 10, 1, 9, 40, 0),
    format: 'mp3',
    id: '1',
    length: '00:07:32',
    size: '7.8 MB',
    source: 'youtube',
    // thumbnail: 'https://i3.ytimg.com/vi/06RlyZxUnVM/maxresdefault.jpg',
    thumbnail:
      'https://i.ytimg.com/vi/6bNZI2GG6Yo/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBtyTUDYVEOE9jk2NeMsJ8zBR5G1Q',
    title: 'Beatles - Abbey Road',
    type: 'audio',
    url: 'https://www.youtube.com/watch?v=uq-_-RJt-E8',
  },
  {
    date: new Date(2022, 1, 22, 14, 22, 10),
    format: 'ogg',
    id: '3',
    length: '00:01:32',
    size: '10.6 MB',
    source: 'vimeo',
    thumbnail: 'https://i3.ytimg.com/vi/3Jw3JdX7KjA/maxresdefault.jpg',
    title: 'The Lion, the Witch and the Wardrobe',
    type: 'audio',
    url: 'https://www.youtube.com/watch?v=uq-_-RJt-E8',
  },
  {
    date: new Date(2020, 11, 25, 9, 44, 10),
    format: 'm4a',
    id: '4',
    length: '00:01:32',
    size: '20.5 MB',
    source: 'youtube',
    thumbnail: 'https://i3.ytimg.com/vi/vpO8chg3HK4/maxresdefault.jpg',
    title: 'Villa Encanto Airbnb 4K NXTLVL HOME  Santa Barbara, CA',
    type: 'audio',
    url: 'https://www.youtube.com/watch?v=uq-_-RJt-E8',
  },
];
export default downloadsAudioDefaults;
