const sources = [
  {
    name: 'Facebook',
    id: 'facebook',
    src: downloadSourceIconFacebook,
    URL: 'https://facebook.com',
    active: false,
    enabled: true,
  },
  {
    name: 'Instagram',
    id: 'instagram',
    src: downloadSourceIconInstagram,
    URL: 'https://instagram.com',
    active: false,
    enabled: true,
  },
  {
    name: 'Pinterest',
    id: 'pinterest',
    src: downloadSourceIconPinterest,
    URL: 'https://pinterest.com',
    active: false,
    enabled: true,
  },
  {
    name: 'Snapchat',
    id: 'snapchat',
    src: downloadSourceIconSnapchat,
    URL: 'https://snapchat.com',
    active: false,
    enabled: true,
  },
  {
    name: 'Soundcloud',
    id: 'soundcloud',
    src: downloadSourceIconSoundcloud,
    URL: 'https://soundcloud.com',
    active: false,
    enabled: true,
  },
  {
    name: 'Tiktok',
    id: 'tiktok',
    src: downloadSourceIconTiktok,
    URL: 'https://tiktok.com',
    active: false,
    enabled: true,
  },
  {
    name: 'Twitch',
    id: 'twitch',
    src: downloadSourceIconTwitch,
    URL: 'https://twitch.com',
    active: false,
    enabled: true,
  },
  {
    name: 'Twitter',
    id: 'twitter',
    src: downloadSourceIconTwitter,
    URL: 'https://twitter.com',
    active: false,
    enabled: false,
  },
  {
    name: 'Vimeo',
    id: 'vimeo',
    src: downloadSourceIconVimeo,
    URL: 'https://vimeo.com',
    active: false,
    enabled: true,
  },
  {
    name: 'Youtube',
    id: 'youtube',
    src: downloadSourceIconYoutube,
    URL: 'https://youtube.com',
    active: true,
    enabled: true,
  },
];
export default sources;
