const adjectiveDescriptiveArr = [
    // emotions/attitudes
    'happy',
    'nostalgic',
    'euphoric',
    'playful',
    'friendly',
    'handsome',
    'chiseled',
    'seductive',
    'cunning',
    'fearless',
    'comforting',
    'comfortable',
    'living',

    'determined',
    'passionate',
    'energetic',
    'indifferent',

    'procrastinating',
    'resourceful',
    'insistent',
    'commanding',
    'charismatic',
    'pensive',
    'curious',
    'confident',
    'optimistic',
    'pessimistic',
    'accompanying',
    'additional',
    'adequate',
    'alternate',
    'alternative',
    'ample',
    'auxiliary',
    'dedicated',
    'DIY',
    'extra',
    'finite',
    'increased',
    'like-new',
    'limited',
    'main',
    'near-infinite',
    'original',
    'reinforcing',
    'reserve',
    'second-hand',
    'spare',
    'spherical',
    'stand-in',
    'substantial',
    'substitute',
    'sufficient',
    'supplemental',
    'supportive',
    'duplicate',

    'sweet',
    'irreverent',
    'wholesome',
    'random',
    'mysterious',
    'merged',
    'stable',
    'descriptive',
    'jettisoned',
    'abandoned',
    'aware',
    'observant',
    'responsive',
    'uninhibited',
    'jet',
    'inhibited',

    'empty',
    'limited',
    'circular',
    'discovered',
    'undiscovered',
    'dancing',
    'electro-swing',
    'swing-dancing',
    'unconstrained',
    'unrestricted',

    'unlimited',
    'green-lit',
    'vast',
    'rainy',
    'ponderous',
    'sentient',
    'cloaked',
    'endless',
    'effervescent',
    'anthropomorphic',
    'animated',
    'cumulus',
    'cirrocumulus',
    'cirrus',
    'nimbus',
    'cumulonimbus',
    'altocumulus',
    'altostratus',
    'stratocumulus',
    'stratus',
    'nimbostratus',
    'convergent',
    'symbolic',
    'stealthy',

    'self-directed',
    'self-aware',

    // human characteristics
    'autodidactic',
    'ambitious',

    // time
    '80\'s',
    '90\'s',
    '70\'s',
    'futuristic',
    'vintage',
    'classic',
    'human-like',
    'asynchronous',
    'synchronous',

    // IMPORTANCE
    'primary',
    'secondary',
    'relevant',
    'dissolved',

    // visual

    'colorful',
    'colorless',
    'monochrome',
    'multicolored',
    'attractive',
    'RGB',
    'profound',

    // tech
    'overclocked',
    'analog',
    'dial-up',
    'fiber-optic',
    'fiber',
    '10-core',
    'hexa-core',
    'octo-core',
    'solid state',
    'offline',
    '9 to 5',
    'online',
    'holiday-ish',
    'New Year\'s',
    'Christmas',
    'Easter',
    'Halloween',
    'Thanksgiving',
    'shadowy',


    'quad-core',
    'VHS',
    'low-level',
    'high-level',
    'algorithmic',
    'mono',
    'greenscreen',
    'surrounding',
    'mechanical',
    'electronic',
    'over-rated',
    'under-rated',
    'noir',
    'streaming',
    'wireframe',
    'disconnected',
    'un-socketed',
    'vertexed',
    'multi-threaded',
    '384-bit',
    'peer-to-peer',
    'cascading',
    'volumetric',
    'neon',
    'thermal',
    'un-recorded',
    'themed',
    'fluorescent',

    '3D',
    '4D',
    '5D',
    '2D',

    'socketed',
    'scenic',
    'lightweight',
    'comedic',
    'dramatic',
    'licensed',
    'unlicensed',
    'dreamy',
    'tranquil',
    'soaring',
    'badly-lit',
    'well-lit',
    'air-conditioned',
    'air-cooled',
    'liquid-cooled',

    'computed',
    'dimensional',
    'de-computed',



    // film/movies
    'time-lapse',
    'gamma',
    'Terminator-like',
    'Thor-like',
    'Odin-like',
    'Loki-like',

    // space
    '2-dimensional',
    '3-dimensional',
    '4-dimensional',
    'solar',
    'astronomical',
    'space',
    'radio',


    'outer',
    'amorphous',
    'silver',
    'color-graded',
    'director\'s cut',
    'inner',
    'exterior',
    'interior',





    // condition
    'refurbished',
    'clean',
    'salvaged',
    'formatted',
    'un-formatted',

    // sound
    'stereo',
    'audible',
    'mono',
    'quiet',
    'noisy',
    'rhythmic',

    // sailing
    'starboard',
    'port-side',
    'below-decks',
    'above-decks',
    'ocean-bound',
    'windward',
    'leeward',
    'anchored',


    // perspective/philosophical
    'subjective',
    'topographical',
    'Gaussian',
    'spatial',
    'planet-side',
    'temporal',
    'transcendental',
    'transformed',
    'cerebral',
    'objective',
    'planetary',
    'major',
    'minor',
    'sharp',
    'flat',
    'dense',
    'abstract',
    'concrete',
    'timed',
    'mega',
    'hyper',
    'neuroscientific',
    'corporate',
    'social',
    'sentinel',

    'discrete',


    // musical
    'synthwave',
    'pitch-perfect',
    'rock-n-roll',
    'jazz',
    'classical',
    'avant-garde',
    'ballet',
    'baroque',
    'choral',
    'classical crossover',
    'concerto',
    'contemporary classical',
    'early',
    'expressionist',
    'high classical',
    'impressionist',
    'medieval',
    'minimalist',
    'modern compositional',
    'modern classical',
    'operatic',
    'orchestral',
    'renaissance',
    'romantic',
    'symphonic',
    'twelve-tone',


    // other
    'archetypical',
    'static',

    // words
    'godly',
    'hybrid',
    'infinite',
    // gaming

    // location/navigation/where/position
    'latitudinal',
    'longitudinal',
    'internal',
    'vacationing',
    'routine',
    'external',
    'alpine',
    'past',
    'stylized',
    'celestial',
    'versioned',
    'subterranean',

    'radial',
    'low-poly',
    'high-poly',
    'cylindrical',
    'sunny',
    'savvy',
    'geometrical',
    'gaming',
    'morphed',
    'whimsical',
    'flying',
    'caffeinated',
    'spherical',
    'shapeshifting',
    'polygonal',
    'expansion',
    'architectural',
    'unparalleled',
    'noteworthy',
    'exceptional',
    'astonishing',
    'thunderous',
    'personal',
    'open',
    'similar',
    'opposing',
    'developer',
    'closed',
    'modular',
    'compatible',
    'unique',
    'extraordinary',
    'invaluable',
    'connected',

    // visual
    'aesthetic',
    'cosmetic',
    'cinematic',
    'invisible',
    'transparent',
    'translucent',
    'opaque',


    // SIZE/shape
    'compact',
    'giant',
    'colossal',
    'tiny',
    'elongated',
    'proportional',


    'built to last',
    // direction/navigation
    'west-bound',
    'east-bound',
    'north-bound',
    'south-bound',

    // status/status
    'unprocessed',

    'thermostatic',
    'behavioral',
    'liquid',
    'guided',
    'accelerative',
    'thermodynamic',
    'preset',
    'pre-determined',
    'fully-managed',
    'genuine',
    'extraordinary',
    'separated',
    'distributed',
    'centralized',
    'de-centralized',

    'functional',
    'synaptic',
    'processed',
    'blissful',
    'non-synthetic',
    'packaged',
    'proxy',
    'hand-crafted',
    'machine',
    'power',
    'emergent',
    'conceptual',
    'multi-versed',
    'aligned',
    'entertaining',
    'supercharged',
    'doppelganger',
    'intelligent',
    'expanded',
    'developed',
    'gravitational',
    'kaleidoscopic',
    'logical',
    'logistical',
    'interesting',

    'procedural',
    'blended',

    'shaded',
    'partial',
    'partitioned',
    'proximity',
    'artificial',
    'authentic',
    'certified',
    'sensible',
    'enjoyable',
    'heavy',
    'twin',
    'triplicate',
    'duplicate',
    'quadruple',
    'beautiful',
    'handsome',
    'light-duty',
    'heavy-duty',
    'declarative',
    'controlled',
    'retro',
    'retrograde',
    'retroactive',

    'modified',


    'asymmetric',
    'symmetrical',
    'parallel',
    'quantum',
    '64-bit',
    '32-bit',
    '8-bit',
    '16-bit',
    '128-bit',
    'atomic',
    'backup',
    '2.9Ghz',
    '3.0Ghz',
    '5 nanometer',
    '50mm',
    'invested',
    '700mm',
    '105mm',
    '20mm',
    '80mm',

    'breathtaking',
    'regenerative',
    'definitive',
    'defined',
    'reactive',
    'clustered',
    'meteoric',
    'balanced',
    'considerable ',
    'contented',
    'light',
    'compound',
    'extensive',
    'complex',
    'split',
    'simple',
    'cozy',
    'critical ',
    'crucial ',
    'parallax',
    'load-balancing',
    'circumpolar',
    'exhilarating',
    'curious',
    'dynamic',
    'inclined',
    'variable',
    'electromagnetic',
    'essential ',
    'exceptional ',
    'extensive ',
    'galactic',
    'high-caliber ',
    'imaginative',
    'positive',
    'collected',
    'exhilarated',
    'uncollected',
    'technological',
    // importance
    'imperative ',
    'influential ',
    'infrared',
    'interplanetary',
    'interstellar',
    'lively',
    'lunar',
    'reasonable',
    'meaningful ',
    'exponential',
    'necessary ',
    'networked',
    'spontaneous',
    'un-spontaneous',
    'nuclear',
    'rotating',
    'aquatic',
    'enigmatic',
    'spatial',
    'contrarian',
    'logarithmic',

    'shredded',
    'space-time',
    'orbital',

    'potent',
    'contented',
    'phased',
    'jovial',
    'quasar',
    'molecular',
    'unpainted',
    'painted',
    'mirrored',
    'reflective',
    'refractive',



    'project',
    'supplied',
    'un-supplied',

    'meta',
    'serverless',
    'serious',
    'significant',
    'routed',

    'stupendous',
    'concentrated',
    'condensed',
    'compressed',
    'telescopic',
    'prerequisite',
    'elective',

    'weapons-grade ',
    'companion',
    'focal',


];

module.exports = adjectiveDescriptiveArr;