const themeColors = {
    buttonActive: 'linear-gradient(268deg, #da2c4d, #f8ab37)',
    // white: '#ffffff',
    // light: '#f0eff3',
    // black: '#000000',
    // darkBlue: '#1f2029',
    // darkLight: '#353746',
    // darkGray: '#777',
    // grey: '#ecedf3',
    // grey2: '#eee',
    dark: {
        primary: '#1f2029',
        secondary: '#353746',
        tertiary: 'black',
        navAButtonBackground: '#353746',
        navAButtonText_active: 'white',
        textPrimary: 'white',
        textSecondary: 'white',
        downloadItemBackgroundColor: '#353746',
        downloadItemBackgroundColor_hover: '#f0eff3',
        downloadItemTextTitle_hover: 'white',
        downloadItemText_hover: 'white',
        downloadItemBorder: '#1f2029',
        navBTextColor: 'white',
        navBTextColor_hover: 'white',
        navBTextColor_active: 'white',
        navBbackground: '#353746',
    },
    light: {
        primary: 'white',
        secondary: 'white',
        tertiary: 'white',
        navAButton_active: 'linear-gradient(268deg, #da2c4d, #f8ab37)',
        navAButtonBackground: 'white',
        navAButtonText_active: 'black',
        textPrimary: 'black',
        textSecondary: '#777',
        downloadItemBackgroundColor: 'white',
        downloadItemBackgroundColor_hover: '#f0eff3',
        downloadItemTextTitle_hover: 'black',
        downloadItemText_hover: '#353746',
        downloadItemBorder: '#eee',
        navBTextColor: 'black',
        navBTextColor_hover: 'white',
        navBTextColor_active: 'white',
        navBbackground: '#f0eff3',
    },
}
module.exports = themeColors;